######################################################################
# AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
#
# This Ansible vars_main.yml is automatically generated by Terraform.
# Any manual changes will be overwritten on next 'terraform apply'.
#
# To modify values, update your Terraform configuration and re-apply.
######################################################################

n8n_db_user: ${db_user}
n8n_db_name: ${db_name}
n8n_db_host: ${db_host}
n8n_db_port: ${db_port}
n8n_db_ssl_enabled: ${db_ssl_enabled}
n8n_port: ${app_port}
