######################################################################
# AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
#
# This Ansible vault_main.yml is automatically generated by Terraform.
# Any manual changes will be overwritten on next 'terraform apply'.
#
# To modify values, update your Terraform configuration and re-apply.
######################################################################

vault_n8n_db_password: ${db_password}
