######################################################################
# AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
#
# This Ansible inventory.yml is automatically generated by Terraform.
# Any manual changes will be overwritten on next 'terraform apply'.
#
# To modify values, update your Terraform configuration and re-apply.
######################################################################

all:
  children:
    n8n:
      hosts:
        web1:
          ansible_host: ${web_1_ip}
          ansible_user: ${vm_user}
          n8n_db_hsot: ${db_host}

        web2:
          ansible_host: ${web_2_ip}
          ansible_user: ${vm_user}
          n8n_db_hsot: ${db_host}
